// <auto-generated />
namespace Patient_History.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Complaints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Complaints));
        
        string IMigrationMetadata.Id
        {
            get { return "201608291149583_Complaints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
